[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[colors.normal]
black   = "#000000"
red     = "#BB0000"
green   = "#00BB00"
yellow  = "#BBBB00"
blue    = "#4A6BFF"
magenta = "#BB00BB"
cyan    = "#00BBBB"
white   = "#BBBBBB"

[colors.bright]
black   = "#555555"
red     = "#FF5555"
green   = "#55FF55"
yellow  = "#FFFF55"
blue    = "#7894FF"
magenta = "#FF55FF"
cyan    = "#55FFFF"
white   = "#FFFFFF"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "FiraCode Nerd Font" }
bold = { family = "FiraCode Nerd Font" }
italic = { family = "FiraCode Nerd Font" }
size = 13

[window]
padding.x = 14
padding.y = 14
decorations = "None"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" },
{ key = "V", mods = "Control", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" },
  { key = "Return", mods = "Shift", chars = "\u001B\r" }
]

[terminal]
osc52 = "CopyPaste"
