set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g history-limit 100000
set-option -s escape-time 0
# status bar
set-option -g status-position top
set-option -g status-justify absolute-centre
set-option -g status-left ""
set-option -g status-right "#S"
set-option -g status-style fg=#a9a9a9,bg=default
