#+TITLE: Emacs Configuration
#+AUTHOR: Ryan Garofano

* Startup & User Interface

No splash screen

#+begin_src emacs-lisp
  (setq inhibit-startup-screen t)
#+end_src

I am using Emacs primarly as a document editor. Prompt me to choose a document at startup.

#+begin_src emacs-lisp
  (add-hook 'emacs-startup-hook
          (lambda ()
            (dired "~/Documents")))
#+end_src

Remove undesirable UI

#+begin_src emacs-lisp
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (blink-cursor-mode -1)
#+end_src

Use relative line numbers

#+begin_src emacs-lisp
  (setq display-line-numbers-type 'visual)
  (global-display-line-numbers-mode t)
#+end_src

* Package Management

Add package repositories and make sure they are up to date

#+begin_src emacs-lisp
  (require 'package)
  (setq package-archives
        '(("gnu"    . "https://elpa.gnu.org/packages/")
          ("nongnu" . "https://elpa.nongnu.org/nongnu/")
          ("melpa"  . "https://melpa.org/packages/")))
  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))
#+end_src

Install the packages I use

#+begin_src emacs-lisp
  (dolist (package '(evil evil-org org-superstar catppuccin-theme))
    (unless (package-installed-p package)
      (package-install package)))
#+end_src

* Evil

I cannot stand editing text without vim motions.

#+begin_src emacs-lisp
  (require 'evil)
  (evil-mode 1)
#+end_src

I like using C-u to scroll up half a page in vim. This should be a default with Evil but it's not.

#+begin_src emacs-lisp
  (with-eval-after-load 'evil
    (define-key evil-normal-state-map (kbd "C-u") #'evil-scroll-up))
#+end_src

Make evil mode play nice with org documents. For example, when I press "o" in a table it will insert a new table row below the cursor. "<" shifts headings.

#+begin_src emacs-lisp
  (require 'evil-org)
  (evil-org-set-key-theme)
  (add-hook 'org-mode-hook #'evil-org-mode)
#+end_src

* Org
** Look and feel
Make it easier to navigate the document by folding up all the headings by default

#+begin_src emacs-lisp
  (setq org-startup-folded t)
#+end_src

Show indents after headings to make the document more readable. Also hide the leading stars in nested headings since indentation makes the level of the
heading clear.

#+begin_src emacs-lisp
  (setq org-startup-indented t)
  (setq org-hide-leading-stars t)
#+end_src

Generate snippets with '<'. For example the src block below can be quickly generated by typing '<s' and then pressing tab. This used to be a default in
org mode but for some reason the maintainers got rid of it. Thus, the org-tempo package was born to restore this functionality.

#+begin_src emacs-lisp
  (require 'org-tempo)
#+end_src

Make heading bullets of different levels more distinct and visually appealing

#+begin_src emacs-lisp
  (with-eval-after-load 'org
    (add-hook 'org-mode-hook #'org-superstar-mode))    
#+end_src

Change indicator for folded headings from default '...'

#+begin_src emacs-lisp
  (setq org-ellipsis " 󱞣")
#+end_src

Make org files read more like a document by applying different font sizes based on heading level

#+begin_src emacs-lisp
  (custom-set-faces
   '(org-level-1 ((t (:inherit outline-1 :height 1.2))))
   '(org-level-2 ((t (:inherit outline-2 :height 1.1))))
   '(org-level-3 ((t (:inherit outline-3 :height 1.05))))
   '(org-level-4 ((t (:inherit outline-4 :height 1.0))))
   '(org-level-5 ((t (:inherit outline-5 :height 1.1))))
   '(org-level-6 ((t (:inherit outline-6 :height 1.1))))
   '(org-level-7 ((t (:inherit outline-7 :height 1.1))))
   '(org-level-8 ((t (:inherit outline-8 :height 1.1)))))
#+end_src

Style document meta data to make it more visually appealing

#+begin_src emacs-lisp
  (custom-set-faces
   '(org-document-title ((t (:height 1.4 :weight bold :underline nil))))
   '(org-document-info ((t (:height 1.1 :foreground "#888888"))))
   '(org-document-info-keyword ((t (:height 0.9 :foreground "#555555")))))
  
  (setq org-hidden-keywords '(title author date))
#+end_src

Evaluate code blocks in an org document!

#+begin_src emacs-lisp
  (with-eval-after-load 'org
    (org-babel-do-load-languages
     'org-babel-load-languages
     '((emacs-lisp . t)
       (python     . t)
       (shell      . t)
       (C          . t)
       (js         . t)
       (ruby       . t)
       (sql        . t))))
#+end_src

** Agenda
Track all org files in ~/Documents

#+begin_src emacs-lisp
  (setq org-agenda-files '("~/Documents"))
#+end_src

Log timestamps when marking a =TODO= as =DONE= and have these show up in the agenda view

#+begin_src emacs-lisp
  (setq org-agenda-start-with-log-mode t)
  (setq org-log-done 'time)
  (setq org-log-into-drawer t)
#+end_src

* Theme

#+begin_src emacs-lisp
  (set-face-attribute 'default nil 
                      :font "JetBrainsMono Nerd Font"
                      :height 120)
  (load-file (expand-file-name "theme.el" user-emacs-directory))
#+end_src
